### ISSUE TITLE
Add ability to disable logging

### ISSUE THREAD

**Issue by bdquig** [zyborg/Zyborg.AWS.Lambda.Kerberos#1]
it would be nice to prevent these messages from sowing up in our CloudWatch logs

**Comment by ebekker** [comment]
The console logging messages?

**Comment by bdquig** [comment]
Sorry. Not sure why I didn't get a notification for this....

Yes, the console messages.

**Comment by ebekker** [comment]
I've added support for specifying an optional [ILogger](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger?view=dotnet-plat-ext-5.0) instance.  And by default it just uses a simple Console Logger instance to preserve the existing _noisy_ behavior.

But you can provide a [NullLogger](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.abstractions.nulllogger.instance) if you just want to silence the default console logging.
